# Generated by Django 5.1.7 on 2025-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='intro',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('staff', 'Staff')], max_length=10),
        ),
    ]
