# Generated by Django 5.1.7 on 2025-05-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0010_remove_category_restaurant_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='lastname',
        ),
    ]
