# Generated by Django 5.1.7 on 2025-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0011_remove_menuitem_available_remove_restaurant_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='table_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
