# Generated by Django 5.1.7 on 2025-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0012_restaurant_table_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
